### ISSUE TITLE
실행 불가 - repository access blocked 

### ISSUE THREAD

**Issue by seongilp** [bang9/lotto-purchase#42]
안녕하세요

이번주부터 실행이 안되는데 에러 메시지가 아래와 같습니다

Error: Repository access blocked

**Comment by bang9** [comment]
안녕하세요 lotto-action 에 관련한 히스토리는 https://velog.io/@bang9dev/14줄의-코드로-로또-자동구매-설정하기 포스팅에서 확인하실 수 있습니다.
감사합니다.
